import type { Metadata } from "next";
import { Inter, Merriweather } from "next/font/google";
import "./globals.css";

import { DirectionProvider } from "@/components/ui/direction";

import { cn } from "@/lib/utils";

const merriweatherHeading = Merriweather({
	subsets: ["latin"],
	variable: "--font-heading",
});

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			className={cn(
				"h-full font-sans antialiased",
				inter.variable,
				merriweatherHeading.variable
			)}
			dir="ltr"
			lang="en"
		>
			<body>
				<DirectionProvider direction="ltr">{children}</DirectionProvider>
			</body>
		</html>
	);
}
