import type { Metadata } from "next";
import "@/styles/globals.css";

import { Footer } from "@/components/layout/footer";
import { Navbar } from "@/components/layout/navbar";
import { DirectionProvider } from "@/components/ui/direction";

import { neueMontreal, seasonMix } from "@/assets/fonts";

import { cn } from "@/lib/utils";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			className={cn(
				"h-full font-sans antialiased",
				neueMontreal.className,
				seasonMix.variable
			)}
			dir="ltr"
			lang="en"
		>
			<body>
				<DirectionProvider direction="ltr">
					<div className="flex min-h-screen flex-col">
						<Navbar />
						<div className="flex-1">{children}</div>
						<Footer />
					</div>
				</DirectionProvider>
			</body>
		</html>
	);
}
